import MdSerializer from "../serializers/mdSerializer";
import PlainSerializer from "../serializers/plainSerializer";

const md = new MdSerializer();
const plain = new PlainSerializer();

/**
 * Converts schema generated by the PlainTextSerializer into scribo compatible schema
 *
 * @param {*} mdEditorState
 */
export function convertPlainTextSchemaToScriboSchema(mdEditorState) {
    // Convert editor state to md plain text
    const mdText = plain.serialize(mdEditorState);

    // Convert mdText to a slate value that works with scribo's schema
    const slateValue = md.deserialize(mdText);

    return slateValue;
}
